routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CommentaireController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\RlApiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PublicController::class, 'home'])->name('public.home');
Route::get('/blog', [PublicController::class, 'blog'])->name('public.blog');
Route::get('/competive/shortly', [RlApiController::class, 'getEventShortly'])->name('public.competitive-shortly');
Route::get('/teams', [RlApiController::class, 'getTeams'])->name('public.teams');
Route::get('/competive/finish-or-in-progress', [RlApiController::class, 'getEventFinish'])->name('public.competitive-finish');
Route::get('/event-details/{id}', [RlApiController::class, 'getEventDetails'])->name('event.event-details');

Route::get('/login',[AuthenticatedSessionController::class, 'store'])->name('login');
Route::get('/register',[AuthenticatedSessionController::class, 'create'])->name('register');

Route::middleware('auth')->group(function () {
    Route::get('/articles/create', [UserController::class, 'create'])->name('articles.create');
    Route::post('/articles/store', [UserController::class, 'store'])->name('articles.store');
    Route::get('/dashboard', [UserController::class, 'index'])->name('dashboard');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::get('/articles/{article}/edit', [UserController::class, 'edit'])->name('articles.edit');
    Route::post('/articles/{article}/update', [UserController::class, 'update'])->name('articles.update');
    Route::get('/articles/{article}/delete', [UserController::class, 'delete'])->name('articles.delete');
    Route::post('/comments/store', [CommentaireController::class, 'store'])->name('comments.store');
});

Route::get('/{user}', [PublicController::class, 'index'])->name('public.index');
Route::get('/{user}/{article}', [PublicController::class, 'show'])->name('public.show');

require __DIR__ . '/auth.php';

app/Models/Article.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Article
 * 
 * @property int $id
 * @property int|null $user_id
 * @property string $title
 * @property string $content
 * @property bool|null $draft
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property string|null $image
 * 
 * @property User|null $user
 * @property Collection|Category[] $categories
 * @property Collection|Comment[] $comments
 * @property Collection|Liker[] $likers
 *
 * @package App\Models
 */
class Article extends Model
{
	protected $table = 'articles';

	protected $casts = [
		'user_id' => 'int',
		'draft' => 'bool'
	];

	protected $fillable = [
		'user_id',
		'title',
		'content',
		'draft',
		'image'
	];

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function categories()
	{
		return $this->belongsToMany(Category::class);
	}

	public function comments()
	{
		return $this->hasMany(Comment::class);
	}

	public function likers()
	{
		return $this->hasMany(Liker::class);
	}
}

app/View/Components/DashLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class DashLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.dash');
    }
}

resources/views/articles/create.blade.php
<x-dash-layout>
    <script type="module" src="{{ asset('upload.js') }}"></script>
    <div class="px-5 text-left">
        <a href="javascript:history.go(-1)" class="text-left text-white hover:text-black-700"><i
                class="fa-solid fa-arrow-left-long"></i></a>
    </div>
    <div class="text-center pb-6">
        <h2 class="font-semibold text-xl text-white leading-tight">
            Créer un article
        </h2>
        @if (session('error'))
        <div class="bg-red-500 text-white p-4 rounded-lg my-6">
            {{ session('error') }}
        </div>
        @endif
    </div>
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 bg-white overflow-hidden shadow-sm sm:rounded-lg p-6 text-gray-900">
        <label for="fileInput" class="block text-sm font-medium text-gray-700">Image de couverture (non modifiable une
            fois l'article publié)</label>
        <input type="file" id="fileInput" name="fileInput">
        <form method="post" action="{{ route('articles.store') }}" class="space-y-6">

            @csrf
            <input type="hidden" id="imageName" name="image">
            <div>
                <!-- Champ pour le titre de l'article -->
                <div>
                    <label for="title" class="block text-sm font-medium text-gray-700">Titre de l'article (max 30
                        caractères)</label>
                    <input type="text" name="title" id="title" placeholder="Entrez le titre ici"
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                        maxlength="30">
                </div>

                <!-- Champ pour le contenu de l'article -->
                <div class="mt-4">
                    <label for="content" class="block text-sm font-medium text-gray-700">Contenu de l'article</label>
                    <textarea rows="10" name="content" id="content" placeholder="Écrivez votre contenu ici"
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"></textarea>
                </div>

                <!-- Sélection des catégories -->
                <div class="mt-4">
                    <fieldset>
                        <legend class="text-sm font-medium text-gray-700">Catégories</legend>
                        <div class="mt-2 space-y-2">
                            @foreach ($categories as $category)
                            <div class="flex items-start">
                                <div class="flex items-center h-5">
                                    <input type="checkbox" name="categories[]" id="categorie_{{ $category->id }}"
                                        value="{{ $category->id }}"
                                        class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                                </div>
                                <div class="ml-3 text-sm">
                                    <label for="categorie_{{ $category->id }}"
                                        class="font-medium text-gray-700">{{ $category->name }}</label>
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </fieldset>
                </div>

                <!-- Option brouillon -->
                <div class="mt-4">
                    <div class="flex items-center">
                        <input type="checkbox" name="draft" id="draft"
                            class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                        <label for="draft" class="ml-2 block text-sm text-gray-900">
                            Enregistrer comme brouillon
                        </label>
                    </div>
                </div>

                <!-- Boutons du formulaire -->
                <div class="flex justify-end space-x-4 mt-4">
                    <button type="button" onclick="javascript:history.go(-1)"
                        class="bg-[#E46A00] hover:bg-[#ffa14f] text-white font-bold py-2 px-4 rounded">
                        Annuler
                    </button>
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Créer l'article
                    </button>
                </div>
            </div>
        </form>
    </div>
</x-dash-layout>

resources/views/articles/edit.blade.php
<x-dash-layout>
    <div class="text-center pb-6">
        <div class="px-5 text-left">
            <a href="javascript:history.go(-1)" class="text-left text-white hover:text-black-700"><i
                    class="fa-solid fa-arrow-left-long"></i></a>
        </div>
        <h2 class="font-semibold text-xl text-white leading-tight">
            Modifier un article
        </h2>
        @if (session('error'))
        <div class="bg-red-500 text-white p-4 rounded-lg my-6">
            {{ session('error') }}
        </div>
        @endif
    </div>
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 bg-white overflow-hidden shadow-sm sm:rounded-lg p-6 text-gray-900">
        <form method="post" action="{{ route('articles.update', $article->id) }}" class="space-y-6">
            @csrf
            <div>

                <!-- Champ pour le titre de l'article -->
                <div>
                    <label for="title" class="block text-sm font-medium text-gray-700">Titre de l'article (max 30
                        caractères)</label>
                    <input type="text" name="title" id="title" value="{{ $article->title }}"
                        placeholder="Entrez le titre ici"
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                        maxlength="30">
                </div>

                <!-- Champ pour le contenu de l'article -->
                <div class="mt-4">
                    <label for="content" class="block text-sm font-medium text-gray-700">Contenu de l'article</label>
                    <textarea rows="10" name="content" id="content" placeholder="Écrivez votre contenu ici"
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">{{ $article->content }}</textarea>
                </div>

                <!-- Sélection des catégories -->
                <div class="mt-4">
                    <fieldset>
                        <legend class="text-sm font-medium text-gray-700">Catégories</legend>
                        <div class="mt-2 space-y-2">
                            @foreach ($categories as $category)
                            <div class="flex items-start">
                                <div class="flex items-center h-5">
                                    <input type="checkbox" name="categories[]" id="categorie_{{ $category->id }}"
                                        value="{{ $category->id }}"
                                        {{ in_array($category->id, $article->categories->pluck('id')->toArray()) ? 'checked' : '' }}
                                        class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                                </div>
                                <div class="ml-3 text-sm">
                                    <label for="categorie_{{ $category->id }}"
                                        class="font-medium text-gray-700">{{ $category->name }}</label>
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </fieldset>
                </div>

                <!-- Option brouillon -->
                <div class="mt-4">
                    <div class="flex items-center">
                        <input type="checkbox" name="draft" id="draft" {{ $article->draft ? 'checked' : '' }}
                            class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                        <label for="draft" class="ml-2 block text-sm text-gray-900">
                            Enregistrer comme brouillon
                        </label>
                    </div>
                </div>

                <!-- Boutons du formulaire -->
                <div class="flex justify-end space-x-4 mt-4">
                    <button type="button" onclick="javascript:history.go(-1)"
                        class="bg-[#E46A00] hover:bg-[#ffa14f] text-white font-bold py-2 px-4 rounded">
                        Annuler
                    </button>
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Modifier l'article
                    </button>
                </div>
            </div>
        </form>
    </div>
</x-dash-layout>